import os

STATUS_COLLECTOR_RABBITMQ_HOST = os.getenv("STATUS_COLLECTOR_RABBITMQ_HOST")
STATUS_COLLECTOR_RABBITMQ_USER = os.getenv("STATUS_COLLECTOR_RABBITMQ_USER")
STATUS_COLLECTOR_RABBITMQ_PWD = os.getenv("STATUS_COLLECTOR_RABBITMQ_PWD")
STATUS_COLLECTOR_RABBITMQ_RK = os.getenv("STATUS_COLLECTOR_RABBITMQ_RK")
STATUS_COLLECTOR_MESOS_MASTER_IP = os.getenv(
    "STATUS_COLLECTOR_MESOS_MASTER_IP")
STATUS_COLLECTOR_RABBITMQ_VHOST = os.getenv("STATUS_COLLECTOR_RABBITMQ_VHOST")
